name: main.yml

on:
  - push

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Build with Gradle
        uses: gradle/gradle-build-action@v2
        with:
          arguments: build